name: worken_sdk
description: "SDK library providing access to make easy and secure transactions with Worken."
version: 0.0.1
homepage: https://www.paidwork.com/

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  injectable: ^2.3.2
  web3dart: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: